repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.88.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
        args:
          - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
      # tfsec is deprecated -> use trivy
      - id: terraform_trivy
        args:
          - --args=--severity=MEDIUM,HIGH,CRITICAL
      - id: terraform_checkov
        args:
          - --args=--skip-check CKV_AWS_144,CKV_AWS_145,CKV2_AWS_62,CKV_AWS_21,CKV_AWS_18,CKV2_AWS_61,CKV2_AWS_6,CKV2_AWS_64

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: \.(md|yml|yaml)$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key
